force-app/main/default/classes/HelloWorld.cls, force-app/main/default/classes/HelloWorld.cls-meta.xml, force-app/main/default/classes/HelloWorldTest.cls, force-app/main/default/classes/HelloWorldTest.cls-meta.xml
=> [DevOps Center] Merge WI-000000 to UAT Release

force-app/main/default/classes/HotFix.cls, force-app/main/default/classes/HotFix.cls-meta.xml, force-app/main/default/classes/HotFixTest.cls, force-app/main/default/classes/HotFixTest.cls-meta.xml
=> [DevOps Center] Merge WI-000001 to Production Hotfix

force-app/main/default/classes/HotFix.cls, force-app/main/default/classes/HotFix.cls-meta.xml, force-app/main/default/classes/HotFixTest.cls, force-app/main/default/classes/HotFixTest.cls-meta.xml
=> [DevOps Center] Merge WI-000001 to Staging Hotfix

force-app/main/default/classes/HotFix.cls, force-app/main/default/classes/HotFix.cls-meta.xml, force-app/main/default/classes/HotFixTest.cls, force-app/main/default/classes/HotFixTest.cls-meta.xml
=> [DevOps Center] Merge WI-000001 to UAT Hotfix

force-app/main/default/classes/HelloWorld.cls, force-app/main/default/classes/HelloWorld.cls-meta.xml, force-app/main/default/classes/HelloWorldTest.cls, force-app/main/default/classes/HelloWorldTest.cls-meta.xml
=> [DevOps Center] Merge WI-000000 to Staging Release

force-app/main/default/classes/HelloWorld.cls, force-app/main/default/classes/HelloWorld.cls-meta.xml, force-app/main/default/classes/HelloWorldTest.cls, force-app/main/default/classes/HelloWorldTest.cls-meta.xml
=> [DevOps Center] Merge WI-000000 to Production Release

force-app/main/default/classes/HotFix.cls
=> [DevOps Center] Merge WI-000003 to UAT Release

force-app/main/default/classes/HotFix.cls
=> [DevOps Center] Merge WI-000002 to Production Hotfix

force-app/main/default/classes/HotFix.cls
=> [DevOps Center] Merge WI-000003 to Staging Release

force-app/main/default/classes/HotFix.cls
=> [DevOps Center] Merge WI-000003 to Production Release

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000004 to UAT Release

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000004 to Staging Release

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000006 to UAT Release

force-app/main/default/objects/Account/Account.object-meta.xml, force-app/main/default/objects/Account/fields/Test_Field__c.field-meta.xml
=> [DevOps Center] Merge WI-000007 to UAT Release

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000008 to Integration

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000008 to UAT

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000009 to Integration

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000009 to UAT

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000009 to Staging

force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml
=> [DevOps Center] Merge WI-000010 to Integration

force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml
=> [DevOps Center] Merge WI-000010 to UAT

force-app/main/default/objects/Contact/Contact.object-meta.xml, force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
=> [DevOps Center] Merge WI-000011 to Integration

force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml
=> [DevOps Center] Merge WI-000010 to Staging

force-app/main/default/objects/Contact/Contact.object-meta.xml, force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
=> [DevOps Center] Merge WI-000011 to Staging

force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml, force-app/main/default/objects/Contact/Contact.object-meta.xml, force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
=> [DevOps Center] Merge Staging to Production

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000012 to Integration

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000013 to UAT

force-app/main/default/classes/HelloWorld.cls
=> [DevOps Center] Merge WI-000013 to Staging

force-app/main/default/classes/HelloWorld.cls
=> Version:  25.02-2

force-app/main/default/classes/HelloWorldTest.cls
=> [DevOps Center] Merge WI-000015 to UAT

force-app/main/default/classes/HelloWorld.cls, force-app/main/default/classes/HelloWorldTest.cls, force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml, force-app/main/default/objects/Contact/Contact.object-meta.xml, force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.
=> [DO NOT MERGE] For DevOps Center use only - Integration to UAT

force-app/main/default/classes/HelloWorldTest.cls
=> [DevOps Center] Merge WI-000015 to Staging

force-app/main/default/classes/HelloWorld.cls, force-app/main/default/classes/HelloWorld.cls-meta.xml, force-app/main/default/classes/HelloWorldTest.cls, force-app/main/default/classes/HelloWorldTest.cls-meta.xml, force-app/main/default/classes/HotFix.cls, force-app/main/default/classes/HotFix.cls-meta.xml, force-app/main/default/classes/HotFixTest.cls, force-app/main/default/classes/HotFixTest.cls-meta.xml, force-app/main/default/objects/Account/Account.object-meta.xml, force-app/main/default/objects/Account/fields/Checked_Box__c.field-meta.xml, force-app/main/default/objects/Account/fields/Test_Field__c.field-meta.xml, force-app/main/default/objects/Contact/Contact.object-meta.xml, force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.
=> [DO NOT MERGE] For DevOps Center use only - UAT to Staging
